elleday/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

import custom_auth_system.views as custom_auth_system_views
import static_pages.views as static_pages_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^places/', include('places.urls', namespace='places')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^$', static_pages_views.homepage, name='homepage'),
    url(r'^contact$', static_pages_views.contact, name='contact'),
    url(r'^company$', static_pages_views.company, name='company'),
    url(r'^logout/', custom_auth_system_views.logout_user, name='logout')
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

places/urls.py
from django.conf.urls import url

import places.views as places_views

urlpatterns = [
    url(r'vote/up', places_views.vote_place_up, name='vote_up'),
    url(r'vote/down', places_views.vote_place_down, name='vote_down'),
    url(r'get', places_views.get_place_by_id, name='get_by_id'),
    url(r'save', places_views.save_place_to_profile, name='save'),
    url(r'remove', places_views.remove_place_from_profile, name='remove'),
    url(r'filter/', places_views.apply_places_filter, name='apply_filters'),
    url(r'search/', places_views.search_places, name='search'),
    url(r'', places_views.show_places_page, name='index'),
]

static_pages/models.py
from __future__ import unicode_literals

# Create your models here.

static_pages/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, template_name='static_pages/index.html')


def company(request):
    return render(request, template_name='static_pages/company.html')


def contact(request):
    return render(request, template_name='static_pages/contact.html')

templates/static_pages/company.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Elleday</title>
        <link href="css/bootstrap.css" rel="stylesheet">
        <link href="css/font-awesome.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet">
        <link rel="stylesheet" href="css/animate.css" type="text/css" />
        <link href='https://fonts.googleapis.com/css?family=Raleway:400,800' rel='stylesheet' type='text/css'>
    </head>
    
<body>

<!-- NAVBAR ----------------------------------------------------------------->    
    <nav class="navbar navbar-default navbar-fixed-top nav-transparent">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">
                    <img class="nav-logo" src="images/logo.png">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">Blog</a></li>
                    <li><a href="#">About</a></li>
                    <div class="btn-group" role="group" aria-label="...">
                        <button type="button" class="btn btn-signup navbar-btn" data-toggle="modal" data-target="#signup">
                            Sign Up
                        </button>
                        <button type="button" class="btn btn-login navbar-btn" data-toggle="modal" data-target="#login">
                            Log In
                        </button>
                    </div>
                </ul>
            </div>
        </div>
    </nav>
    <div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="signuplabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="signuplabel">Sign Up For Elleday</h2>
                </div>
                <div class="modal-body">
                    <form id="signup" method="post" action="/signup">
                        <input name="user[name]" type="text" placeholder="Type your username here" required="required" class="input">
                        <input name="user[password]" type="password" placeholder="Choose a password" required="required" class="input">
                        <input name="user[password2]" type="password" placeholder="Confirm your password" required="required" class="input">
                        <input name="user[email]" type="email" placeholder="E-mail address" class="input">
                        <input type="submit" value="Sign me up!" class="inputButton">
                        <hr>
                        <div class="text-center">
                            <button class="btn btn-social btn-google text-center">
                                <span class="fa fa-google"></span> <h6 class="social-button">Sign in with Google</h6>
                            </button>
                        </div>
                        <br>
                        <div class="text-center">
                            <button class="btn btn-social btn-facebook text-center">
                                <span class="fa fa-facebook"></span> <h6 class="social-button">Sign in with Facebook</h6>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="loginlabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="loginlabel">Log In To Elleday</h2>
                </div>
                <div class="modal-body">
                    <form id="login" method="post" action="/login">
                        <input name="user[name]" type="text" placeholder="Type your username here" required="required" class="input">
                        <input name="user[password]" type="password" placeholder="Enter your password" required="required" class="input">
                        <input type="submit" value="Log me in!" class="inputButton">
                        <hr>
                        <div class="text-center">
                            <button class="btn btn-social btn-google text-center">
                                <span class="fa fa-google"></span> <h6 class="social-button">Sign in with Google</h6>
                            </button>
                        </div>
                        <br>
                        <div class="text-center">
                            <button class="btn btn-social btn-facebook text-center">
                                <span class="fa fa-facebook"></span> <h6 class="social-button">Sign in with Facebook</h6>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

<!-- HEADER ----------------------------------------------------------------->  
    <div class="container-fluid about-bg">
        <div class="row company-header">
            <h1 class="white-font">Your City Guide</h1>
        </div>
        <div class="row margin-top-spacing">
            <ul id="inline-list">
                <li class="active"><a href="/company.html">Company</a></li>
                <li><a href="/values.html">Values</a></li> 
                <li><a href="/team.html">Team</a></li>
                <li><a href="/contact.html">Contact</a></li> 
            </ul>
            <div class="container">
                <div class="row margin-spacing">
                    <div class="col-sm-3">
                        <h5 class="about-h2">Our Mission</h5>
                    </div>
                    <div class="col-sm-9">
                        <p class="text-left">
                            Elleday helps anyone discover their next favourite places!<br><br>
                            We help you find your way to explore the places you’ll love the most! Do more, travel, discover and make the most of your time!
                        </p>
                    </div>
                </div>
            <hr>
            </div>
            <div class="container">
                <div class="row margin-spacing">
                    <div class="col-sm-4">
                        <h1 class="about-h1">2016</h1>
                        <p class="text-left">Elleday is starting out in Tallinn, Estonia and we’re making our way to more cities soon!</p>
                    </div>
                    <div class="col-sm-4">
                        <h1 class="about-h1">AI</h1>
                        <p class="text-left">
                            Our personalised suggestions are getting better with time - we use a machine learning algorithm to develop better connections for you!
                        </p>
                    </div>
                    <div class="col-sm-4">
                        <h1 class="about-h1">25%</h1>
                        <p class="text-left">
                            We’re sharing 25 per cent of each city’s revenue with it’s moderators! Review places, earn karma and make some extra living!
                        </p>
                    </div>
                </div>
            <hr>
            </div>
            <div class="container">
                <div class="row margin-spacing">
                    <div class="col-sm-12">
                        <img src="images/events-featured-2.jpg" class="about-image-1">
                    </div>
                </div>
                <div class="row margin-spacing">
                    <div class="col-sm-6">
                        <img src="images/events-featured-2.jpg" class="about-image-1">
                    </div>
                    <div class="col-sm-6">
                        <img src="images/events-featured-2.jpg" class="about-image-1">
                    </div>
                </div>
                <div class="row margin-spacing">
                    <div class="col-sm-12">
                        <img src="images/events-featured-2.jpg" class="about-image-1">
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- FOOTER -----------------------------------------------------------------> 
    <footer class="container-fluid footer-bg">
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <h4>About</h4>
                    <h6>
                        <ul>
                            <li><a href="#">Team & Mission</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </h6>
                </div>
                <div class="col-sm-4">
                    <h4>Partner Hub</h4>
                    <h6>
                        <ul>
                            <li><a href="#">Learn</a></li>
                            <li><a href="#">Promote</a></li>
                            <li><a href="#">Track</a></li>
                        </ul>
                    </h6>
                </div>
                <div class="col-sm-4">
                    <h4>Moderator Hub</h4>
                    <h6>
                        <ul>
                            <li><a href="#">Learn</a></li>
                            <li><a href="#">Apply</a></li>
                            <li><a href="#">Real Elles</a></li>
                        </ul>
                    </h6>
                </div>
            </div>
            <br>
            <h6>
                Please do let us know if you have any questions or feedback at: <a href="mailto:hello@elleday.com" class="pink-font">hello@elleday.com</a><br> © Elleday 2016. <a href="#">Privacy</a>, <a>terms & conditions apply</a>.
            </h6>
        </div>
    </footer>

<!-- JAVASCRIPT -----------------------------------------------------------------> 
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="js/bootstrap.js"></script>
    </body>
</html>

templates/static_pages/index.html
{% extends 'base_layout.html' %}
{% load staticfiles %}

{% block title %}Elleday{% endblock %}

{% block content %}
    <div class="container-fluid header-bg">
        <div class="container">
            <div class="row">
                <img src="{% static 'images/elleday-mascot.png' %}" class="mascot">
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h1>Discover a <span class="pink-font">great</span> day</h1>
                    <br>
                    <h5 class="line-height-2em">
                        The easiest city guide to <span class="pink-font">Tallinn</span>!<br>Elleday helps you on your
                        way to great moments - explore places for your next activity hassle free!
                    </h5>
                </div>
            </div>
            <br>
            <div class="row text-center">
                <form method="get" action="{% url 'places:index' %}">
                    <button class="btn btn-search btn-lg" type="submit">Explore All Places</button>
                </form>
            </div>
            <div class="row margin-top-spacing">
                <br><br>
                <!-- Carousel 1 -->
                <div class="col-sm-6">
                    <h2 class="text-left grey-font">Featured Places</h2>
                    <div id="carousel-slide-1" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-slide-1" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-slide-1" data-slide-to="1"></li>
                            <li data-target="#carousel-slide-1" data-slide-to="2"></li>
                        </ol>
                        <!-- Wrapper -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="images/places-featured-1.jpg" alt="Image Descrption 1">
                                <div class="carousel-caption">
                                    Image Caption 1
                                </div>
                            </div>
                            <div class="item">
                                <img src="images/places-featured-2.jpg" alt="Image Descrption 2">
                                <div class="carousel-caption">
                                    Image Caption 2
                                </div>
                            </div>
                            <div class="item">
                                <img src="images/places-featured-3.jpg" alt="Image Descrption 3">
                                <div class="carousel-caption">
                                    Image Caption 3
                                </div>
                            </div>
                        </div>
                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-slide-1" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-slide-1" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
                <!-- Carousel 2 -->
                <div class="col-sm-6">
                    <h2 class="text-left grey-font">Trending Places</h2>
                    <div id="carousel-slide-2" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-slide-2" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-slide-2" data-slide-to="1"></li>
                            <li data-target="#carousel-slide-2" data-slide-to="2"></li>
                        </ol>
                        <!-- Wrapper -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <img src="images/events-featured-1.jpg" alt="Image Descrption 1">
                                <div class="carousel-caption">
                                    Image Caption 1
                                </div>
                            </div>
                            <div class="item">
                                <img src="images/events-featured-2.jpg" alt="Image Descrption 2">
                                <div class="carousel-caption">
                                    Image Caption 2
                                </div>
                            </div>
                            <div class="item">
                                <img src="images/events-featured-3.jpg" alt="Image Descrption 3">
                                <div class="carousel-caption">
                                    Image Caption 3
                                </div>
                            </div>
                        </div>
                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-slide-2" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="right carousel-control" href="#carousel-slide-2" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
            <br><br>
            <div class="row margin-top-spacing">
                <div class="col-md-6 col-md-offset-3">
                    <form action="{% url 'places:search' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group input-group-lg">
                                <input type="text" class="form-control" placeholder="Where do you want to go?"
                                       name="search_query" aria-describedby="sizing-addon1">
                                <span class="input-group-btn">
                                    <button class="btn btn-search" type="submit">Search Now</button>
                                </span>
                        </div>
                     </form>
                    <p class="text-right"><i>Search by name, tags or categories.</i></p>
                </div>
            </div>
        </div>
    </div>

    <!-- TOP STORIES ----------------------------------------------------------------->
    <div class="container-fluid top-stories-bg">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h3>
                        Keep up with stories from Tallinn with<br>
                        Elle's <span class="pink-font">Blog</span> @ Elleday
                    </h3>
                </div>
            </div>
            <br><br>
            <div class="row text-center">
                <div class="col-sm-4">
                    <div class="top-stories-1">
                        <h6>Featured post by <span class="pink-font">Jane Smith</span></h6>
                        <br>
                        <h4>Great heading to a blog article</h4>
                        <h6>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac gravida sem, sit amet
                            ullamcorper urna. Aliquam eget metus feugiat, venenatis odio id, ultricies.
                        </h6>
                        <br>
                        <button type="button" class="btn btn-default btn-blog">Read Now</button>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="top-stories-2">
                        <h6>Featured post by <span class="pink-font">Jane Smith</span></h6>
                        <br>
                        <h4>Great heading to a blog article</h4>
                        <h6>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac gravida sem, sit amet
                            ullamcorper urna. Aliquam eget metus feugiat, venenatis odio id, ultricies.
                        </h6>
                        <br>
                        <button type="button" class="btn btn-default btn-blog">Read Now</button>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="top-stories-3">
                        <h6>Featured post by <span class="pink-font">Jane Smith</span></h6>
                        <br>
                        <h4>Great heading to a blog article</h4>
                        <h6>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac gravida sem, sit amet
                            ullamcorper urna. Aliquam eget metus feugiat, venenatis odio id, ultricies.
                        </h6>
                        <br>
                        <button type="button" class="btn btn-default btn-blog">Read Now</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- FEATURES ----------------------------------------------------------------->
    <div class="container-fluid features-bg">
        <div class="container">
            <h2>Happy exploring with <span class="pink-font">Elleday</span>!</h2><br>
            <p>
                We're still just getting started so much more is on it’s way! Feel free to get in touch to give us
                feedback on our features<br>or if you’d like us to come to your city next!
            </p>
            <div class="row">
                <div class="col-sm-4">
                    <div class="feature-icons">
                        <img src="{% static 'images/icon-1.png' %}" class="img-responsive img-center"><br>
                        <p>More Cities</p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="feature-icons">
                        <img src="{% static 'images/icon-2.png' %}" class="img-responsive img-center"><br>
                        <p>Better Personalisation</p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="feature-icons">
                        <img src="{% static 'images/icon-3.png' %}" class="img-responsive img-center"><br>
                        <p>More Moderator Benefits</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}