elleday/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

import custom_auth_system.views as custom_auth_system_views
import static_pages.views as static_pages_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^places/', include('places.urls', namespace='places')),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^$', static_pages_views.homepage, name='homepage'),
    url(r'^contact$', static_pages_views.contact, name='contact'),
    url(r'^company$', static_pages_views.company, name='company'),
    url(r'^logout/', custom_auth_system_views.logout_user, name='logout')
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

places/urls.py
from django.conf.urls import url

import places.views as places_views

urlpatterns = [
    url(r'vote/up', places_views.vote_place_up, name='vote_up'),
    url(r'vote/down', places_views.vote_place_down, name='vote_down'),
    url(r'get', places_views.get_place_by_id, name='get_by_id'),
    url(r'save', places_views.save_place_to_profile, name='save'),
    url(r'remove', places_views.remove_place_from_profile, name='remove'),
    url(r'filter/', places_views.apply_places_filter, name='apply_filters'),
    url(r'search/', places_views.search_places, name='search'),
    url(r'', places_views.show_places_page, name='index'),
]

places/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from taggit.managers import TaggableManager


class Place(models.Model):
    def __unicode__(self):
        return u'{0}'.format(self.title)

    main_image = models.ImageField(verbose_name='Main image', blank=True, null=True, upload_to='places/main_images',
                                   default='places/main_images/placeholder.jpg')
    title = models.CharField(max_length=256, verbose_name='Place title', blank=False, null=False)
    address = models.CharField(max_length=256, verbose_name='Place address', blank=False, null=False)
    categories = models.ManyToManyField('Category', blank=False, verbose_name='Place categories')
    tags = models.ManyToManyField('Tag', blank=True, verbose_name='Place tags', related_name='place')
    phone = models.CharField(max_length=64, blank=True, null=False, default='')
    budget = models.IntegerField(blank=False, null=False, default=0)
    style = models.IntegerField(blank=False, null=False, default=0)
    adventure = models.IntegerField(blank=False, null=False, default=0)
    landscape = models.IntegerField(blank=False, null=False, default=0)
    must_see = models.IntegerField(blank=False, null=False, default=0)
    energy = models.IntegerField(blank=False, null=False, default=0)
    rating = models.IntegerField(verbose_name='Rating of a place', default=0, null=False)
    positive_votes = models.IntegerField(verbose_name='Number of positive votes',
                                         default=0)
    negative_votes = models.IntegerField(verbose_name='Number of negative votes',
                                         default=0)
    images = models.ManyToManyField('PlaceImage', verbose_name='Place images', related_name='place', blank=True)

    @classmethod
    def random(cls, quantity=1):
        result = list()

        for i in range(quantity):
            result.append(cls.objects.order_by('?').first())

        return result

    def vote_up(self):
        self.rating += 1
        self.positive_votes += 1
        self.save()

    def vote_down(self):
        self.rating -= 1
        self.negative_votes += 1
        self.save()

    def total_votes(self):
        return self.positive_votes + self.negative_votes


class PlaceImage(models.Model):
    def __unicode__(self):
        return u'{0}'.format(self.description)

    class Meta:
        verbose_name = "Place image"
        verbose_name_plural = "Place images"

    image = models.ImageField(verbose_name='Image for place', upload_to='places_images')
    description = models.CharField(max_length=64)


class Category(models.Model):
    def __unicode__(self):
        return u'{0}'.format(self.category)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=64, unique=True)


class Tag(models.Model):
    def __unicode__(self):
        return u'{0} ({1})'.format(self.name, self.place.title)

    name = models.CharField(verbose_name='Tag name', max_length=64)
    rating = models.IntegerField(verbose_name='Tag rating', blank=False, null=False, default=0)

places/forms.py
from django import forms


class PlacesFiltersForm(forms.Form):
    category_eat = forms.BooleanField()
    category_nightlife = forms.BooleanField()
    category_sights = forms.BooleanField()
    category_shop = forms.BooleanField()
    category_culture = forms.BooleanField()
    category_fun = forms.BooleanField()
    category_sport = forms.BooleanField()
    category_relax = forms.BooleanField()
    category_saved = forms.BooleanField()
    budget_range = forms.IntegerField(min_value=1, max_value=5)
    style_range = forms.IntegerField(min_value=1, max_value=5)
    adventure_range = forms.IntegerField(min_value=1, max_value=5)
    landscape_range = forms.IntegerField(min_value=1, max_value=3)
    must_see_range = forms.IntegerField(min_value=1, max_value=5)
    energy_range = forms.IntegerField(min_value=1, max_value=5)

places/views.py
from django.shortcuts import render_to_response, render, redirect
from django.views.decorators.csrf import csrf_exempt
from django_ajax.decorators import ajax

from custom_auth_system.models import UserProfile
from places.models import Place

range_to_int_mapping_5 = {
    "1": (0, 20),
    "2": (20, 40),
    "3": (40, 60),
    "4": (60, 80),
    "5": (80, 100),
}

range_to_int_mapping_3 = {
    "1": (0, 33),
    "2": (33, 66),
    "3": (99, 100),
}


def show_places_page(request):
    places = Place.random(10)
    context = {'places': places}
    return render(request, 'places/places-page.html', context=context)


@ajax
def vote_place_up(request):
    place_id = request.GET.get('place_id')
    place = Place.objects.get(id=place_id)
    place.vote_up()
    resp = {'result': place.positive_votes, 'total': place.total_votes()}
    return resp


@ajax
def vote_place_down(request):
    place_id = request.GET.get('place_id')
    place = Place.objects.get(id=place_id)
    place.vote_down()
    resp = {'result': place.negative_votes, 'total': place.total_votes()}
    return resp


def get_place_directions(request, place_id):
    pass


@ajax
def get_place_by_id(request):
    place_id = request.GET.get('place_id')
    place = Place.objects.get(id=place_id)
    context = {'place': place,
               'reviews': place.reviews.all(),
               'reviews_len': len(place.reviews.all()),
               'images': place.images.all()}
    return render(request, 'places/info.html', context=context)


@ajax
def save_place_to_profile(request):
    if request.method == "POST":
        place_id = request.POST.get('place_id')
        place = Place.objects.get(id=place_id)
        user = UserProfile.objects.get(user_id=request.user)
        user.saved_places.add(place)
        user.save()
        return {'result': True}


@ajax
def remove_place_from_profile(request):
    if request.method == "POST":
        place_id = request.POST.get('place_id')
        place = Place.objects.get(id=place_id)
        user = UserProfile.objects.get(user_id=request.user)
        user.saved_places.remove(place)
        user.save()
        return {'result': True}


@csrf_exempt
def apply_places_filter(request):
    if request.method == "POST":
        query_dict = request.POST

        budget_value = query_dict.get('budget-range')
        style_value = query_dict.get('style-range')
        adventure_value = query_dict.get('adventure-range')
        landscape_value = query_dict.get('landscape-range')
        must_see_value = query_dict.get('must-see-range')
        energy_value = query_dict.get('energy-range')
        tags = [x.lower() for x in query_dict.getlist('tags')]
        categories_names = [('eat-option', 'Eat'),
                            ('nightlife-option', 'Nightlife'),
                            ('sights-option', 'Sights'),
                            ('shop-option', 'Shop'),
                            ('culture-option', 'Culture'),
                            ('fun-option', 'Fun'),
                            ('sport-option', 'Sport'),
                            ('relax-option', 'Relax'),
                            ('saved-option', 'Saved')]
        selected_categories = []
        for k in categories_names:
            if query_dict.get(k[0]):
                selected_categories.append(k[1])

        places = Place.objects.filter(budget__range=range_to_int_mapping_5[budget_value],
                                      style__range=range_to_int_mapping_5[style_value],
                                      adventure__range=range_to_int_mapping_5[adventure_value],
                                      landscape__range=range_to_int_mapping_3[landscape_value],
                                      must_see__range=range_to_int_mapping_5[must_see_value],
                                      energy__range=range_to_int_mapping_5[energy_value],
                                      categories__category__in=selected_categories).distinct()

        result_places = []
        for place in places:
            r = check_tags(place, tags)
            if r:
                result_places.append(r)

        context = {'places': result_places}

        return render(request, 'places/places-page.html', context=context)

    return render(request, "places/places-page.html")


def check_tags(place, tags):
    if not tags:
        return place

    place_tags = [x.name.lower() for x in place.tags.all()]
    for tag in tags:
        if not tag.lower() in place_tags:
            return None

    return place


def search_by_tag(search_query, place):
    place_tags = [x.name.lower() for x in place.tags.all()]
    for tag in place_tags:
        if tag in search_query.lower():
            return place
    return None


def search_places(request):
    if request.method == "POST":
        search_query = request.POST.get('search_query')
        search_query = search_query.lower()
        result_places = Place.objects.filter(title__icontains=search_query).distinct()
        if not result_places:
            places = Place.objects.all()
            result_places = []
            for place in places:
                r = search_by_tag(search_query, place)
                if r:
                    result_places.append(r)
        context = {'places': result_places}

        return render(request, 'places/places-page.html', context=context)
    else:
        return redirect('places.index')

templates/places/place_voting.html
{% extends 'places/info.html' %}

{% block place_voting %}
    <br>
    <p>{{ place.total_votes }} people rated this place</p>
    <p class="glyphicon-p">
        <a href="{% url 'vote_place_up' place_id=place.id %}">
            <span id="positive-votes-{{ place.id }}">{{ place.positive_votes }}</span>
            <span class="glyphicon glyphicon-thumbs-up glyphicon-spacing-2 margin-left"></span>
        </a>

        <a href="{% url 'vote_place_down' place_id=place.id %}">
            <span class="glyphicon glyphicon-thumbs-down glyphicon-spacing-2 margin-right"></span>
            <span id="negative-votes-{{ place.id }}">{{ place.negative_votes }}</span>
        </a>
    </p>
    <hr class="green-line">
    <hr class="red-line">
    <br><br>
{% endblock %}

templates/places/places-page.html
{% extends 'base_layout.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container-fluid places-page">
        <!-- Left Column Starts -->
        <div class="col-xs-12 col-sm-6 scroll-active padding-nil">
            <form id="filter-form" action="{% url 'places:apply_filters' %}" method="post">
                <!-- Filter Starts -->
                <div id="flip-h">
                    {% csrf_token %}
                    <div class="row">
                        <br/>
                        <div class="col-sm-3">
                            <h4 class="grey-font">Tags</h4>
                        </div>
                        <div class="col-sm-9">
                            <ol class="tags">
                                <li class="tagAdd taglist">
                                    <input type="text" id="search-field"
                                           placeholder="Type and press 'Ctrl+Enter'">
                                </li>
                            </ol>
                        </div>
                    </div>
                    <h4 class="grey-font" id="flip">MORE FILTERS <span class="glyphicon glyphicon-chevron-down"></span>
                    </h4>
                </div>
                <div id="panel">
                    <div class="row filter-blocks">
                        <div class="col-sm-3">
                            <h4 class="grey-font">Categories</h4>
                        </div>
                        <div class="col-sm-9">
                            <div data-toggle="buttons">
                                <label class="btn btn-default filter-radio">
                                    <input type="checkbox" name="eat-option" id="option1">
                                    <span class="radio-dot"></span>
                                    <p class="grey-font filter-radio-text"><span
                                            class="glyphicon glyphicon-cutlery glyphicon-spacing"
                                            aria-hidden="true"></span>
                                        Eat</p>
                                </label>
                                <label class="btn btn-default filter-radio">
                                    <input type="checkbox" name="nightlife-option" id="option2">
                                    <span class="radio-dot"></span>
                                    <p class="grey-font filter-radio-text"><span
                                            class="glyphicon glyphicon-glass glyphicon-spacing"
                                            aria-hidden="true"></span>
                                        Nightlife</p>
                                </label>
                                <label class="btn btn-default filter-radio">
                                    <input type="checkbox" name="sights-option" id="option2">
                                    <span class="radio-dot"></span>
                                    <p class="grey-font filter-radio-text"><span
                                            class="glyphicon glyphicon-camera glyphicon-spacing"
                                            aria-hidden="true"></span>
                                        Sights</p>
                                </label>
                                <label class="btn btn-default filter-radio">
                                    <input type="checkbox" name="shop-option" id="option2">
                                    <span class="radio-dot"></span>
                                    <p class="grey-font filter-radio-text"><span
                                            class="glyphicon glyphicon-shopping-cart glyphicon-spacing"
                                            aria-hidden="true"></span> Shop</p>
                                </label>
                                <label class="btn btn-default filter-radio">
                                    <input type="checkbox" name="culture-option" id="option2">
                                    <span class="radio-dot"></span>
                                    <p class="grey-font filter-radio-text"><span
                                            class="glyphicon glyphicon-globe glyphicon-spacing"
                                            aria-hidden="true"></span>
                                        Culture</p>
                                </label>
                                <label class="btn btn-default filter-radio">
                                    <input type="checkbox" name="fun-option" id="option2">
                                    <span class="radio-dot"></span>
                                    <p class="grey-font filter-radio-text"><span
                                            class="glyphicon glyphicon-equalizer glyphicon-spacing"
                                            aria-hidden="true"></span> Fun</p>
                                </label>
                                <label class="btn btn-default filter-radio">
                                    <input type="checkbox" name="sport-option" id="option2">
                                    <span class="radio-dot"></span>
                                    <p class="grey-font filter-radio-text"><span
                                            class="glyphicon glyphicon-bullhorn glyphicon-spacing"
                                            aria-hidden="true"></span> Sport</p>
                                </label>
                                <label class="btn btn-default filter-radio">
                                    <input type="checkbox" name="relax-option" id="option2">
                                    <span class="radio-dot"></span>
                                    <p class="grey-font filter-radio-text"><span
                                            class="glyphicon glyphicon-knight glyphicon-spacing"
                                            aria-hidden="true"></span>
                                        Relax</p>
                                </label>
                                <label class="btn btn-default filter-radio">
                                    <input type="checkbox" name="saved-option" id="saved">
                                    <span class="radio-dot"></span>
                                    <p class="grey-font filter-radio-text"><span
                                            class="glyphicon glyphicon-floppy-saved glyphicon-spacing"
                                            aria-hidden="true"></span> Saved</p>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="row filter-blocks-last hidden-xs">
                        <div class="row">
                            <div class="col-sm-3 filter-title">
                                <h4 class="grey-font">Preferences</h4>
                            </div>
                            <div class="col-sm-9"></div>
                        </div>
                        <div class="col-sm-6">
                            <h6 class="grey-font text-left">Budget</h6>
                            <div class="range">
                                <output id="budget-range-text">Moderate</output>
                                <input type="range" name="budget-range" id="budget-range" min="1" max="5" value="3"
                                       onchange="changeBudgetText(value)">
                            </div>
                            <hr class="filter-divider">
                            <h6 class="grey-font text-left">Adventure</h6>
                            <div class="range">
                                <output id="adventure-range-text">Let's See</output>
                                <input type="range" name="adventure-range" id="adventure-range" min="1" max="5"
                                       value="3"
                                       onchange="changeAdventureText(value)">
                            </div>
                            <hr class="filter-divider">
                            <h6 class="grey-font text-left">Energy</h6>
                            <div class="range">
                                <output id="energy-range-text">Moderate</output>
                                <input type="range" name="energy-range" id="energy-range" min="1" max="5" value="3"
                                       onchange="changeEnergyText(value)">
                            </div>
                            <hr class="filter-divider">
                        </div>
                        <div class="col-sm-6">
                            <h6 class="grey-font text-left">Style</h6>
                            <div class="range">
                                <output id="style-range-text">Regular</output>
                                <input type="range" name="style-range" id="style-range" min="1" max="5" value="3"
                                       onchange="changeStyleText(value)">
                            </div>
                            <hr class="filter-divider">
                            <h6 class="grey-font text-left">Landscape</h6>
                            <div class="range">
                                <output id="landscape-range-text">Any</output>
                                <input type="range" name="landscape-range" id="landscape-range" min="1" max="3"
                                       value="2"
                                       onchange="changeLandscapeText(value)">
                            </div>
                            <hr class="filter-divider">
                            <h6 class="grey-font text-left">Must See</h6>
                            <div class="range">
                                <output id="must-see-range-text">For longer stay</output>
                                <input type="range" name="must-see-range" id="must-see-range" min="1" max="5" value="3"
                                       onchange="changeMustSeeText(value)">
                            </div>
                            <hr class="filter-divider">
                        </div>
                    </div>
                    <div class="row text-right filter-blocks-last">
                        <button type="submit" class="btn btn-default btn-pink" id="apply-changes">Apply Changes</button>
                    </div>

                </div>
            </form>
            <!-- Filter Ends -->
            <div class="mass-selection">
                {% for place in places %}
                    {% if forloop.counter0|divisibleby:2 or forloop.first %}
                    <div class="row results-spacing">
                    {% endif %}
                        <div class="col-sm-6">
                            <!-- Img 1 -->
                            <div class="caption" onclick="showInfoForPlace({{ place.id }})">

                            <span id="img-trigger-1">
                                <img src="{{ place.main_image.url }}" class="front-image">
                                <br><br>
                                    <p>{{ place.title }}</p>
                            </span>
                            </div>
                        </div>
                        <div id="info-div">
                            {% block info_div %}{% endblock %}
                        </div>
                    {% if not forloop.counter0|divisibleby:2 or forloop.last %}
                    </div>
                    {% endif %}
                {% empty %}
                    <div class="row results-spacing">
                        <h3 class="pink-font">Sorry, no places found :-(</h3>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!-- Left Column Ends -->

        <!-- Right Column Starts -->
        <div class="hidden-xs col-sm-6 padding-nil bg-grey">
            <div class="input-group map-search-bar">
                <form action="{% url 'places:search' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" class="form-control no-glow" placeholder="Search Places" name="search_query">
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"
                                                                           aria-hidden="true"></span></input>
                    </span>
                    </div>
                </form>
            </div>
            {#        <iframe width='100%' height='800px' frameBorder='0'#}
            {#                src='https://api.mapbox.com/styles/v1/teamlday/cihdujt2v00mabdm1ia2pytm5.html?title=true&access_token=pk.eyJ1IjoidGVhbWxkYXkiLCJhIjoiY2loMjVwN3g3MDBvNHY1bTdvczdnN2owMyJ9.gxHMuIWMBMGfvKPgf25VCA#15.07/59.4338/24.7451'></iframe>#}
        </div>
        <!-- Right Column Ends -->
    </div>
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/range-names.js' %}"></script>
    <script src="{% static 'django_ajax/js/jquery.ajax.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/info-div.js' %}"></script>
{% endblock %}
<!-- Filter Bar -->